<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Bookmaker;

class BookmakerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Bookmaker::query()->updateOrCreate(
            ['key' => '1xbet'],
            ['key' => '1xbet',
                'name' => '1XBET',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => '1xbet.svg',
                'logo_color' => '#1A5685',
                'promo_code' => 'GENER55',
                'bonus_available' => 0,
                'bonus_label_1_en' => '$130 Bonus',
                'bonus_label_1_es' => 'Bono de $130',
                'bonus_label_1_fr' => 'Bonus de $130',
                'bonus_label_1_pt' => 'Bônus de $130',
                'bonus_label_2_en' => '1xBet Promo Code: GENER55 gives you the opportunity to receive a $30 bonus',
                'bonus_label_2_es' => 'Código promocional 1xBet: GENER55 permite obtener un bono de $30',
                'bonus_label_2_fr' => 'Code promotionnel 1xBet : GENER55 permet d’obtenir un bonus de 30 $',
                'bonus_label_2_pt' => 'Código promocional 1xBet: GENER55 permite receber um bônus de $30',
                'warning_en' => 'T&Cs apply. Over 18s only.',
                'warning_es' => 'Se aplican términos y condiciones.',
                'warning_fr' => "Conditions générales applicables.",
                'warning_pt' => 'Aplicam-se termos e condições.',
                'licensed' => 'Curacao, eGaming, Kahnawake Gaming Commission',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'info-en@1xbet.com',
                'phone' => '+49 800 5889574',
                'active' => 1,
                'order' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'melbet'],
            ['key' => 'melbet',
                'name' => 'MelBet',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => 'melbet.svg',
                'logo_color' => '#000809',
                'promo_code' => 'CLUB500',
                'bonus_available' => 0,
                'bonus_label_1_en' => '$130 Bonus - 30% extra',
                'bonus_label_1_es' => '$130 Bono - 30% extra',
                'bonus_label_1_fr' => '$130 Bonus - 30% supplémentaire',
                'bonus_label_1_pt' => '$130 Bônus - 30% extra',
                'bonus_label_2_en' => 'Promo Code: CLUB500',
                'bonus_label_2_es' => 'Código promocional: CLUB500',
                'bonus_label_2_fr' => 'Code promotionnel : CLUB500',
                'bonus_label_2_pt' => 'Código promocional: CLUB500',
                'warning_en' => '18+',
                'warning_es' => '18+',
                'warning_fr' => '18+',
                'warning_pt' => '18+',
                'licensed' => 'Curacao',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'info-en@melbet.org',
                'phone' => '+442038077601',
                'active' => 1,
                'order' => 2,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'betwinner'],
            ['key' => 'betwinner',
             'name' => 'BetWinner',
             'url' => 'https://1wfzws.life/?p=ayxs',
             'logo' => 'betwinner.svg',
             'logo_color' => '#1a674b',
             'promo_code' => 'NEWBONUS',
             'bonus_available' => 0,
             'bonus_label_1_en' => '$130 Free Bet',
             'bonus_label_1_es' => 'Apuesta gratuita de $130',
             'bonus_label_1_fr' => 'Pari gratuit de $130',
             'bonus_label_1_pt' => 'Aposta grátis de $130',
             'bonus_label_2_en' => 'BetWinner Promo Code: NEWBONUS gives you the opportunity to receive a $130 bonus',
             'bonus_label_2_es' => 'Código promocional de BetWinner: NEWBONUS te da la oportunidad de recibir un bono de $130',
             'bonus_label_2_fr' => 'Code promotionnel de BetWinner : NEWBONUS vous donne la possibilité de recevoir un bonus de 130 $',
             'bonus_label_2_pt' => 'Código promocional da BetWinner: NEWBONUS dá a oportunidade de receber um bônus de $130',
             'warning_en' => '18+ only. Gamble responsibly. Ts and Cs apply.',
             'warning_es' => 'Solo para mayores de 18 años. Juega con responsabilidad. Aplican términos y condiciones.',
             'warning_fr' => "Réservé aux 18 ans et plus. Jouez de manière responsable. Termes et conditions s'appliquent.",
             'warning_pt' => 'Apenas para maiores de 18 anos. Jogue com responsabilidade. Aplicam-se termos e condições.',
             'licensed' => 'Curacao',
             'streaming' => 1,
             'tested' => 1,
             'email' => 'support@betwinner.com',
             'phone' => '+44 203 936 2996',
             'active' => 1,
             'order' => 3,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '1win'],
            ['key' => '1win',
                'name' => '1win',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => '1win.svg',
                'logo_color' => '#1b243a',
                'promo_code' => '1W500GAX',
                'bonus_available' => 0,
                'bonus_label_1_en' => '$205 Bonus',
                'bonus_label_1_es' => 'Bono de $205',
                'bonus_label_1_fr' => 'Bonus de $205',
                'bonus_label_1_pt' => 'Bônus de $205',
                'bonus_label_2_en' => 'Promo Code: 1W500GAX',
                'bonus_label_2_es' => 'Código promocional: 1W500GAX',
                'bonus_label_2_fr' => 'Code promotionnel : 1W500GAX',
                'bonus_label_2_pt' => 'Código promocional: 1W500GAX',
                'warning_en' => '18+. T&Cs apply.',
                'warning_es' => '18+. Aplican términos y condiciones.',
                'warning_fr' => "18+. Termes et conditions s'appliquent.",
                'warning_pt' => '18+. Aplicam-se termos e condições.',
                'licensed' => '',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'support@1win.xyz',
                'phone' => '',
                'active' => 1,
                'order' => 4,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'mostbet'],
            ['key' => 'mostbet',
                'name' => 'MOSTBET',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => 'mostbet.svg',
                'logo_color' => '#003b77',
                'promo_code' => 'HUGE',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Deposit $200',
                'bonus_label_1_es' => 'Deposita $200',
                'bonus_label_1_fr' => 'Déposez $200',
                'bonus_label_1_pt' => 'Deposite $200',
                'bonus_label_2_en' => 'MOSTBET Promo Code: HUGE gives you the opportunity to receive a 150% bonus',
                'bonus_label_2_es' => 'Código promocional de MOSTBET: HUGE te da la oportunidad de recibir un bono de 150%',
                'bonus_label_2_fr' => 'Code promotionnel de MOSTBET : HUGE vous donne la possibilité de recevoir un bonus de 150%',
                'bonus_label_2_pt' => 'Código promocional da MOSTBET: HUGE dá a oportunidade de receber um bônus de 150%',
                'warning_en' => 'Deposit up to $200. Get a 150% bonus up to $300 & 250 Free Spins. 18+ only. T&Cs apply.',
                'warning_es' => 'Deposita hasta 200$. Obtén un bono del 150% hasta 300$ y 250 giros gratis. Solo para mayores de 18 años. Se aplican Términos y Condiciones.',
                'warning_fr' => "Déposez jusqu’à 200$. Obtenez un bonus de 150% jusqu’à 300$ et 250 tours gratuits. Réservé aux 18 ans et plus. Conditions générales applicables.",
                'warning_pt' => 'Deposite até 200$. Receba um bônus de 150% até 300$ e 250 rodadas grátis. Apenas para maiores de 18 anos. Aplicam-se os Termos e Condições.',
                'licensed' => 'Curacao',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'SUPPORT-EN@MOSTBET.COM',
                'phone' => '',
                'active' => 1,
                'order' => 5,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'paripesa'],
            ['key' => 'paripesa',
                'name' => 'PARIPESA',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => 'paripesa.svg',
                'logo_color' => '#0f2595',
                'promo_code' => 'TOPBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => '$100 Bonus + 30% extra',
                'bonus_label_1_es' => '$100 Bono + 30% extra',
                'bonus_label_1_fr' => '$100 Bonus + 30% supplémentaire',
                'bonus_label_1_pt' => '$100 Bônus + 30% extra',
                'bonus_label_2_en' => 'Promo Code: TOPBONUS',
                'bonus_label_2_es' => 'Código promocional: TOPBONUS',
                'bonus_label_2_fr' => 'Code promotionnel : TOPBONUS',
                'bonus_label_2_pt' => 'Código promocional: TOPBONUS',
                'warning_en' => '',
                'warning_es' => '',
                'warning_fr' => '',
                'warning_pt' => '',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'support-en@PariPesa.com',
                'phone' => '+254 700 123456',
                'active' => 1,
                'order' => 6,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '4rabet'],
            ['key' => '4rabet',
                'name' => '4RABET',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => '4rabet.svg',
                'logo_color' => '#0f0710',
                'promo_code' => '4rasport22',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Welcome Bonus 200%',
                'bonus_label_1_es' => 'Bono de bienvenida del 200%',
                'bonus_label_1_fr' => 'Bonus de bienvenue de 200%',
                'bonus_label_1_pt' => 'Bónus de boas-vindas de 200%',
                'bonus_label_2_en' => '4RABET Promo Code: 4rasport22 gives you the opportunity to receive a 200% bonus',
                'bonus_label_2_es' => 'Código promocional de 4RABET: 4rasport22 te da la oportunidad de recibir un bono de 200%',
                'bonus_label_2_fr' => 'Code promotionnel de 4RABET : 4rasport22 vous donne la possibilité de recevoir un bonus de 200%',
                'bonus_label_2_pt' => 'Código promocional da 4RABET: 4rasport22 dá a oportunidade de receber um bônus de 200%',
                'warning_en' => '',
                'warning_es' => '',
                'warning_fr' => '',
                'warning_pt' => '',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 0,
                'email' => 'support@4rabet.com',
                'phone' => '',
                'active' => 1,
                'order' => 7,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '888starz'],
            ['key' => '888starz',
             'name' => '888starz',
             'url' => 'https://1wfzws.life/?p=ayxs',
             'logo' => '888starz.svg',
             'logo_color' => '#0f0710',
             'promo_code' => 'WORLDCUP',
             'bonus_available' => 0,
             'bonus_label_1_en' => 'Deposit €130 Get €130',
             'bonus_label_1_es' => 'Deposita €130 y recibe €130',
             'bonus_label_1_fr' => 'Déposez €130 et recevez €130',
             'bonus_label_1_pt' => 'Deposite €130 e receba €130',
                'bonus_label_2_en' => 'Promo Code: WORLDCUP',
                'bonus_label_2_es' => 'Código promocional: WORLDCUP',
                'bonus_label_2_fr' => 'Code promotionnel : WORLDCUP',
                'bonus_label_2_pt' => 'Código promocional: WORLDCUP',
             'warning_en' => '18+ only. T&Cs apply.',
             'warning_es' => 'Solo para mayores de 18 años. Aplican términos y condiciones.',
             'warning_fr' => "Réservé aux 18 ans et plus. Termes et conditions s'appliquent.",
             'warning_pt' => 'Apenas para maiores de 18 anos. Aplicam-se termos e condições.',
             'licensed' => 'Curacao',
             'streaming' => 0,
             'tested' => 1,
             'email' => 'support-en@888starz.bet',
             'phone' => '+357 97630833',
             'active' => 1,
             'order' => 8,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'megapari'],
            ['key' => 'megapari',
                'name' => 'MEGAPARI',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => 'megapari.svg',
                'logo_color' => '#000000',
                'promo_code' => 'NEWBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Deposit $130 Get $130',
                'bonus_label_1_es' => 'Deposita $130 y recibe $130',
                'bonus_label_1_fr' => 'Déposez $130 et recevez $130',
                'bonus_label_1_pt' => 'Deposite $130 e receba $130',
                'bonus_label_2_en' => 'Promo Code: NEWBONUS',
                'bonus_label_2_es' => 'Código promocional: NEWBONUS',
                'bonus_label_2_fr' => 'Code promotionnel : NEWBONUS',
                'bonus_label_2_pt' => 'Código promocional: NEWBONUS',
                'warning_en' => 'Over 18s.',
                'warning_es' => 'Mayores de 18 años.',
                'warning_fr' => "Réservé aux plus de 18 ans.",
                'warning_pt' => 'Apenas para maiores de 18 anos.',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'support@megapari.com',
                'phone' => '+441863440619',
                'active' => 1,
                'order' => 9,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '22bet'],
            ['key' => '22bet',
                'name' => '22BET',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => '22bet.svg',
                'logo_color' => '#064146',
                'promo_code' => 'HUGE',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Bet €150 Get €150',
                'bonus_label_1_es' => 'Apuesta 150€ y recibe 150€',
                'bonus_label_1_fr' => 'Pariez 150€ et recevez 150€',
                'bonus_label_1_pt' => 'Aposte 150€ e receba 150€',
                'bonus_label_2_en' => 'Promo Code: HUGE',
                'bonus_label_2_es' => 'Código promocional: HUGE',
                'bonus_label_2_fr' => 'Code promotionnel : HUGE',
                'bonus_label_2_pt' => 'Código promocional: HUGE',
                'warning_en' => '18+ only. Ts and Cs apply.',
                'warning_es' => 'Solo para mayores de 18 años. Se aplican términos y condiciones.',
                'warning_fr' => "Réservé aux 18 ans et plus. Conditions générales applicables.",
                'warning_pt' => 'Apenas para maiores de 18 anos. Aplicam-se termos e condições.',
                'licensed' => 'UK Gambling Commission, Curacao',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'support-en@22bet.com',
                'phone' => '+357 99 816806',
                'active' => 1,
                'order' => 10,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'linebet'],
            ['key' => 'linebet',
                'name' => 'Linebet',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => 'linebet.svg',
                'logo_color' => '#204f14',
                'promo_code' => 'BNB777',
                'bonus_available' => 0,
                'bonus_label_1_en' => '$130 Bonus',
                'bonus_label_1_es' => 'Bono de $130',
                'bonus_label_1_fr' => 'Bonus de $130',
                'bonus_label_1_pt' => 'Bônus de $130',
                'bonus_label_2_en' => 'Linebet Promo Code: BNB777 gives you the opportunity to receive a $130 bonus',
                'bonus_label_2_es' => 'Código promocional de Linebet: BNB777 te da la oportunidad de recibir un bono de $130',
                'bonus_label_2_fr' => 'Code promotionnel de Linebet : BNB777 vous donne la possibilité de recevoir un bonus de $130',
                'bonus_label_2_pt' => 'Código promocional da Linebet: BNB777 dá a oportunidade de receber um bônus de $130',
                'warning_en' => '18+. T&Cs apply.',
                'warning_es' => '18+. Aplican términos y condiciones.',
                'warning_fr' => "18+. Termes et conditions s'appliquent.",
                'warning_pt' => '18+. Aplicam-se termos e condições.',
                'licensed' => 'Curacao',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'support-in@linebet.com',
                'phone' => '+44 20 4577 0803',
                'active' => 1,
                'order' => 11,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '20bet'],
            ['key' => '20bet',
                'name' => '20BET',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => '20bet.svg',
                'logo_color' => '#081d36',
                'promo_code' => 'MISSING',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Welcome Bonus €100',
                'bonus_label_1_es' => 'Bono de bienvenida del €100',
                'bonus_label_1_fr' => 'Bonus de bienvenue de €100',
                'bonus_label_1_pt' => 'Bónus de boas-vindas de €100',
                'bonus_label_2_en' => '20BET Promo Code: MISSING gives you the opportunity to receive +120 free spins',
                'bonus_label_2_es' => 'Código promocional de 20BET: MISSING te da la oportunidad de recibir +120 giros gratis',
                'bonus_label_2_fr' => 'Code promotionnel 20BET : MISSING vous donne la possibilité de recevoir +120 tours gratuits',
                'bonus_label_2_pt' => 'Código promocional da 20BET: MISSING dá a você a oportunidade de receber +120 rodadas grátis',
                'warning_en' => 'Register and get welcome bonus €100.',
                'warning_es' => 'Regístrate y recibe un bono de bienvenida de 100€.',
                'warning_fr' => 'Inscrivez-vous et recevez un bonus de bienvenue de 100€.',
                'warning_pt' => 'Registe-se e receba um bónus de boas-vindas de 100€.',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'support@20bet.com',
                'phone' => '',
                'active' => 1,
                'order' => 12,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'betandyou'],
            ['key' => 'betandyou',
                'name' => 'BETANDYOU',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => 'betandyou.svg',
                'logo_color' => '#000000',
                'promo_code' => 'MAXBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Deposit $130 Get $130',
                'bonus_label_1_es' => 'Deposita $130 y recibe $130',
                'bonus_label_1_fr' => 'Déposez $130 et recevez $130',
                'bonus_label_1_pt' => 'Deposite $130 e receba $130',
                'bonus_label_2_en' => 'BETANDYOU Promo Code: MAXBONUS gives you the opportunity to receive a 130%',
                'bonus_label_2_es' => 'Código promocional de BETANDYOU: MAXBONUS te da la oportunidad de recibir un bono de 130%',
                'bonus_label_2_fr' => 'Code promotionnel de BETANDYOU : MAXBONUS vous donne la possibilité de recevoir un bonus de 130%',
                'bonus_label_2_pt' => 'Código promocional da BETANDYOU: MAXBONUS dá a oportunidade de receber um bônus de 130%',
                'warning_en' => '18+ only. T&Cs apply.',
                'warning_es' => 'Solo para mayores de 18 años. Se aplican términos y condiciones.',
                'warning_fr' => "Réservé aux 18 ans et plus. Conditions générales applicables.",
                'warning_pt' => 'Apenas para maiores de 18 anos. Aplicam-se termos e condições.',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'support-en@betandyou.com',
                'phone' => '',
                'active' => 1,
                'order' => 13,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'ivibet'],
            ['key' => 'ivibet',
                'name' => 'ivibet',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => 'ivibet.svg',
                'logo_color' => '#07C99A',
                'promo_code' => 'MAXBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => '$150 Free Bet',
                'bonus_label_1_es' => 'Apuesta gratuita de $130',
                'bonus_label_1_fr' => 'Pari gratuit de $130',
                'bonus_label_1_pt' => 'Aposta grátis de $130',
                'bonus_label_2_en' => 'Promo Code: MAXBONUS',
                'bonus_label_2_es' => 'Código promocional: MAXBONUS',
                'bonus_label_2_fr' => 'Code promotionnel : MAXBONUS',
                'bonus_label_2_pt' => 'Código promocional: MAXBONUS',
                'warning_en' => '18+. T&Cs apply.',
                'warning_es' => '18+. Se aplican términos y condiciones.',
                'warning_fr' => "18+. Conditions générales applicables.",
                'warning_pt' => '18+. Aplicam-se termos e condições.',
                'licensed' => 'Kahnawake',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'support@ivibet.com',
                'phone' => '',
                'active' => 1,
                'order' => 14,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '1xbit'],
            ['key' => '1xbit',
                'name' => '1xBit',
                'url' => 'https://1wfzws.life/?p=ayxs',
                'logo' => '1xbit.svg',
                'logo_color' => '#212121',
                'promo_code' => 'NEWBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => '7 BTC bonus',
                'bonus_label_1_es' => 'Bono de 7 BTC',
                'bonus_label_1_fr' => 'Bonus de 7 BTC',
                'bonus_label_1_pt' => 'Bónus de 7 BTC',
                'bonus_label_2_en' => 'Promo Code: NEWBONUS',
                'bonus_label_2_es' => 'Código promocional: NEWBONUS',
                'bonus_label_2_fr' => 'Code promotionnel : NEWBONUS',
                'bonus_label_2_pt' => 'Código promocional: NEWBONUS',
                'warning_en' => '18+ only. Minimum deposit of 5 mBTC. 40x wagering applies. Ts and Cs apply.',
                'warning_es' => 'Solo mayores de 18 años. Depósito mínimo de 5 mBTC. Se aplica un requisito de apuesta de 40x. Aplican Términos y Condiciones.',
                'warning_fr' => "Réservé aux 18 ans et plus. Dépôt minimum de 5 mBTC. Conditions de mise de 40x. Termes et conditions s’appliquent.",
                'warning_pt' => 'Apenas para maiores de 18 anos. Depósito mínimo de 5 mBTC. Requisitos de aposta de 40x aplicam-se. Termos e Condições aplicáveis.',
                'licensed' => 'Curacao',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'support-en@1x-bit.com',
                'phone' => '',
                'active' => 1,
                'order' => 15,
            ]
        );
    }
}
