<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Bookmaker;

class BookmakerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Bookmaker::query()->updateOrCreate(
            ['key' => '1xbet'],
            ['key' => '1xbet',
                'name' => '1XBET',
                'url' => 'new-1xbet.com',
                'logo' => '1xbet.svg',
                'logo_color' => '#1A5685',
                'promo_code' => 'NEWBONUS',
                'bonus_available' => 1,
                'bonus_label_1_en' => '$130 Bonus',
                'bonus_label_1_es' => 'Bono de $130',
                'bonus_label_1_fr' => 'Bonus de $130',
                'bonus_label_1_pt' => 'Bônus de $130',
                'bonus_label_2_en' => 'Use code NEWBONUS for $30 extra bonus',
                'bonus_label_2_es' => 'Usa el código NEWBONUS para obtener $30 de bono extra',
                'bonus_label_2_fr' => 'Utilisez le code NEWBONUS pour obtenir 30$ de bonus supplémentaire',
                'bonus_label_2_pt' => 'Use o código NEWBONUS para ganhar um bônus extra de $30',
                'warning_en' => 'Get $30 more bonus when you use the 1xbet code NEWBONUS. T&Cs apply. Over 18s only. If you make a $100 first deposit without a promo code, you will receive a $100 bonus, if you use promo code NEWBONUS and then deposit $100, you will receive a $130 bonus.',
                'warning_es' => 'Obtén $30 de bono extra cuando uses el código 1xbet NEWBONUS. Se aplican términos y condiciones. Solo mayores de 18 años. Si realizas un primer depósito de $100 sin código promocional, recibirás un bono de $100. Si usas el código promocional NEWBONUS y luego depositas $100, recibirás un bono de $130.',
                'warning_fr' => "Obtenez 30$ de bonus supplémentaire en utilisant le code 1xbet NEWBONUS. Conditions générales applicables. Réservé aux personnes de plus de 18 ans. Si vous effectuez un premier dépôt de 100$ sans code promo, vous recevrez un bonus de 100$. Si vous utilisez le code promo NEWBONUS et déposez ensuite 100$, vous recevrez un bonus de 130$.",
                'warning_pt' => 'Receba $30 de bônus extra ao usar o código 1xbet NEWBONUS. Aplicam-se termos e condições. Apenas para maiores de 18 anos. Se você fizer um primeiro depósito de $100 sem código promocional, receberá um bônus de $100. Se usar o código promocional NEWBONUS e depois depositar $100, receberá um bônus de $130.',
                'licensed' => 'Curacao, eGaming, Kahnawake Gaming Commission',
                'streaming' => 1,
                'tested' => 1,
                'email' => 'info-en@1xbet.com',
                'phone' => '+49 800 5889574',
                'active' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'melbet'],
            ['key' => 'melbet',
                'name' => 'MelBet',
                'url' => 'melbet-077269.top',
                'logo' => 'melbet.svg',
                'logo_color' => '#000809',
                'promo_code' => 'NEWBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => '$130 Bonus - 30% extra',
                'bonus_label_1_es' => '$130 Bono - 30% extra',
                'bonus_label_1_fr' => '$130 Bonus - 30% supplémentaire',
                'bonus_label_1_pt' => '$130 Bônus - 30% extra',
                'bonus_label_2_en' => 'Use code NEWBONUS',
                'bonus_label_2_es' => 'Usa el código NEWBONUS',
                'bonus_label_2_fr' => 'Utilisez le code NEWBONUS',
                'bonus_label_2_pt' => 'Use o código NEWBONUS',
                'warning_en' => 'Use the MelBet Promo code NEWBONUS to get 30% extra. 18+',
                'warning_es' => 'Usa el código promocional de MelBet NEWBONUS para obtener un 30% extra. 18+',
                'warning_fr' => 'Utilisez le code promo MelBet NEWBONUS pour obtenir 30% de bonus supplémentaire. 18+',
                'warning_pt' => 'Use o código promocional da MELBET “NEWBONUS” para ganhar 30% extra. 18+',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'info-en@melbet.org',
                'phone' => '+442038077601',
                'active' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'betwinner'],
            ['key' => 'betwinner',
             'name' => 'BetWinner',
             'url' => 'prmbw.com/bw-sport/?p=/user/registration/',
             'logo' => 'betwinner.svg',
             'logo_color' => '#1a674b',
             'promo_code' => 'NEWBONUS',
             'bonus_available' => 0,
             'bonus_label_1_en' => '$130 Free Bet',
             'bonus_label_1_es' => 'Apuesta gratuita de $130',
             'bonus_label_1_fr' => 'Pari gratuit de $130',
             'bonus_label_1_pt' => 'Aposta grátis de $130',
             'bonus_label_2_en' => 'Use code NEWBONUS for $130 bonus',
             'bonus_label_2_es' => 'Usa el código NEWBONUS para obtener un bono de $130',
             'bonus_label_2_fr' => 'Utilisez le code NEWBONUS pour un bonus de $130',
             'bonus_label_2_pt' => 'Use o código NEWBONUS para ganhar um bônus de $130',
             'warning_en' => '18+ only. Gamble responsibly. Ts and Cs apply.',
             'warning_es' => 'Solo para mayores de 18 años. Juega con responsabilidad. Aplican términos y condiciones.',
             'warning_fr' => "Réservé aux 18 ans et plus. Jouez de manière responsable. Termes et conditions s'appliquent.",
             'warning_pt' => 'Apenas para maiores de 18 anos. Jogue com responsabilidade. Aplicam-se termos e condições.',
             'licensed' => 'Curacao',
             'streaming' => 0,
             'tested' => 1,
             'email' => 'support@betwinner.com',
             'phone' => '+44 203 936 2996',
             'active' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '1win'],
            ['key' => '1win',
                'name' => '1win',
                'url' => 'www.1win.global',
                'logo' => '1win.svg',
                'logo_color' => '#1b243a',
                'promo_code' => 'XLBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => '$205 Bonus',
                'bonus_label_1_es' => 'Bono de $205',
                'bonus_label_1_fr' => 'Bonus de $205',
                'bonus_label_1_pt' => 'Bônus de $205',
                'bonus_label_2_en' => 'Use promo code XLBONUS',
                'bonus_label_2_es' => 'Usa el código promocional XLBONUS',
                'bonus_label_2_fr' => 'Utilisez le code promo XLBONUS',
                'bonus_label_2_pt' => 'Use o código promocional XLBONUS',
                'warning_en' => 'Register with Promo code XLBONUS. 18+. T&Cs apply.',
                'warning_es' => 'Regístrate con el código promocional XLBONUS. 18+. Aplican términos y condiciones.',
                'warning_fr' => "Inscrivez-vous avec le code promo XLBONUS. 18+. Termes et conditions s'appliquent.",
                'warning_pt' => 'Registe-se com o código promocional XLBONUS. 18+. Aplicam-se termos e condições.',
                'licensed' => '',
                'streaming' => 0,
                'tested' => 0,
                'email' => '',
                'phone' => '',
                'active' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'mostbet'],
            ['key' => 'mostbet',
                'name' => 'MOSTBET',
                'url' => 'mostbet.com',
                'logo' => 'mostbet.svg',
                'logo_color' => '#003b77',
                'promo_code' => 'HUGE',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Deposit $200',
                'bonus_label_1_es' => 'Deposita $200',
                'bonus_label_1_fr' => 'Déposez $200',
                'bonus_label_1_pt' => 'Deposite $200',
                'bonus_label_2_en' => 'Get 150% bonus with promocode HUGE',
                'bonus_label_2_es' => 'Obtén un bono del 150% con el código promocional HUGE',
                'bonus_label_2_fr' => 'Obtenez un bonus de 150% avec le code promo HUGE',
                'bonus_label_2_pt' => 'Receba um bônus de 150% com o código promocional HUGE',
                'warning_en' => 'Use promo code HUGE. Deposit up to $200. Get a 150% bonus up to $300 & 250 Free Spins. 18+ only. T&Cs apply.',
                'warning_es' => 'Usa el código promocional HUGE. Deposita hasta 200$. Obtén un bono del 150% hasta 300$ y 250 giros gratis. Solo para mayores de 18 años. Se aplican Términos y Condiciones.',
                'warning_fr' => "Utilisez le code promo HUGE. Déposez jusqu’à 200$. Obtenez un bonus de 150% jusqu’à 300$ et 250 tours gratuits. Réservé aux 18 ans et plus. Conditions générales applicables.",
                'warning_pt' => 'Use o código promocional HUGE. Deposite até 200$. Receba um bônus de 150% até 300$ e 250 rodadas grátis. Apenas para maiores de 18 anos. Aplicam-se os Termos e Condições.',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'SUPPORT-EN@MOSTBET.COM',
                'phone' => '',
                'active' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'paripesa'],
            ['key' => 'paripesa',
                'name' => 'PARIPESA',
                'url' => 'paripesa.com',
                'logo' => 'paripesa.svg',
                'logo_color' => '#0f2595',
                'promo_code' => 'TOPBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => '$100 Bonus + 30% extra',
                'bonus_label_1_es' => '$100 Bono + 30% extra',
                'bonus_label_1_fr' => '$100 Bonus + 30% supplémentaire',
                'bonus_label_1_pt' => '$100 Bônus + 30% extra',
                'bonus_label_2_en' => 'Use code TOPBONUS',
                'bonus_label_2_es' => 'Usa el código TOPBONUS',
                'bonus_label_2_fr' => 'Utilisez le code TOPBONUS',
                'bonus_label_2_pt' => 'Use o código TOPBONUS',
                'warning_en' => 'Register with confirmation code TOPBONUS and get 30% extra on top of the $100 bonus.',
                'warning_es' => 'Regístrate con el código de confirmación TOPBONUS y obtén un 30% extra además del bono de 100$.',
                'warning_fr' => 'Inscrivez-vous avec le code de confirmation TOPBONUS et recevez 30% de bonus supplémentaire en plus du bonus de 100$.',
                'warning_pt' => 'Registe-se com o código de confirmação TOPBONUS e receba 30% extra além do bônus de 100$.',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'support-en@PariPesa.com',
                'phone' => '+254 700 123456',
                'active' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '4rabet'],
            ['key' => '4rabet',
                'name' => '4RABET',
                'url' => '4rabet-play.com',
                'logo' => '4rabet.svg',
                'logo_color' => '#0f0710',
                'promo_code' => '4rasport22',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Welcome Bonus 200%',
                'bonus_label_1_es' => 'Bono de bienvenida del 200%',
                'bonus_label_1_fr' => 'Bonus de bienvenue de 200%',
                'bonus_label_1_pt' => 'Bónus de boas-vindas de 200%',
                'bonus_label_2_en' => 'Use promo code 4rasport22',
                'bonus_label_2_es' => 'Usa el código promocional 4rasport22',
                'bonus_label_2_fr' => 'Utilisez le code promo 4rasport22',
                'bonus_label_2_pt' => 'Use o código promocional 4rasport22',
                'warning_en' => 'Register with promo code 4rasport22 and get welcome bonus 200%.',
                'warning_es' => 'Regístrate con el código promocional 4rasport22 y obtén un bono de bienvenida del 200%.',
                'warning_fr' => 'Inscrivez-vous avec le code promo 4rasport22 et obtenez un bonus de bienvenue de 200%.',
                'warning_pt' => 'Registe-se com o código promocional 4rasport22 e receba um bónus de boas-vindas de 200%.',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 0,
                'email' => 'support@4rabet.com',
                'phone' => '',
                'active' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '888starz'],
            ['key' => '888starz',
             'name' => '888starz',
             'url' => 'hopufoa6.site/registration',
             'logo' => '888starz.svg',
             'logo_color' => '#0f0710',
             'promo_code' => 'NEWBONUS',
             'bonus_available' => 0,
             'bonus_label_1_en' => 'Deposit €130 Get €130',
             'bonus_label_1_es' => 'Deposita €130 y recibe €130',
             'bonus_label_1_fr' => 'Déposez €130 et recevez €130',
             'bonus_label_1_pt' => 'Deposite €130 e receba €130',
             'bonus_label_2_en' => 'Use promo code NEWBONUS',
             'bonus_label_2_es' => 'Usa el código promocional NEWBONUS',
             'bonus_label_2_fr' => 'Utilisez le code promo NEWBONUS',
             'bonus_label_2_pt' => 'Use o código promocional NEWBONUS',
             'warning_en' => '18+ only. T&Cs apply. Register with promo code NEWBONUS and unlock the 100% 1st deposit welcome bonus up to €/$130 from 888starz.bet.',
             'warning_es' => 'Solo para mayores de 18 años. Aplican términos y condiciones. Regístrate con el código promocional NEWBONUS y desbloquea el bono de bienvenida del 100% en tu primer depósito, hasta €/$130 en 888starz.bet.',
             'warning_fr' => "Réservé aux 18 ans et plus. Termes et conditions s'appliquent. Inscrivez-vous avec le code promo NEWBONUS et débloquez le bonus de bienvenue de 100% sur le premier dépôt, jusqu'à €/$130. sur 888starz.bet.",
             'warning_pt' => 'Apenas para maiores de 18 anos. Aplicam-se termos e condições. Registe-se com o código promocional NEWBONUS e desbloqueie o bônus de boas-vindas de 100% no primeiro depósito, até €/$130 no 888starz.bet.',
             'licensed' => 'Curacao',
             'streaming' => 0,
             'tested' => 1,
             'email' => 'support-en@888starz.bet',
             'phone' => '+357 97630833',
             'active' => 1,
                ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'megapari'],
            ['key' => 'megapari',
                'name' => 'MEGAPARI',
                'url' => 'megapari.com',
                'logo' => 'megapari.svg',
                'logo_color' => '#000000',
                'promo_code' => 'NEWBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Deposit $130 Get $130',
                'bonus_label_1_es' => 'Deposita $130 y recibe $130',
                'bonus_label_1_fr' => 'Déposez $130 et recevez $130',
                'bonus_label_1_pt' => 'Deposite $130 e receba $130',
                'bonus_label_2_en' => 'Use promo code NEWBONUS',
                'bonus_label_2_es' => 'Usa el código promocional NEWBONUS',
                'bonus_label_2_fr' => 'Utilisez le code promo NEWBONUS',
                'bonus_label_2_pt' => 'Use o código promocional NEWBONUS',
                'warning_en' => 'Over 18s. Register with the promo code NEWBONUS.',
                'warning_es' => 'Mayores de 18 años. Regístrate con el código promocional NEWBONUS.',
                'warning_fr' => "Réservé aux plus de 18 ans. Inscrivez-vous avec le code promo NEWBONUS.",
                'warning_pt' => 'Apenas para maiores de 18 anos. Registe-se com o código promocional NEWBONUS.',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'support-en@megapari.com',
                'phone' => '+44-20-3808-8565',
                'active' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '22bet'],
            ['key' => '22bet',
                'name' => '22BET',
                'url' => '22bet.com',
                'logo' => '22bet.svg',
                'logo_color' => '#064146',
                'promo_code' => 'HUGE',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Bet €150 Get €150',
                'bonus_label_1_es' => 'Apuesta 150€ y recibe 150€',
                'bonus_label_1_fr' => 'Pariez 150€ et recevez 150€',
                'bonus_label_1_pt' => 'Aposte 150€ e receba 150€',
                'bonus_label_2_en' => 'Use promo code HUGE',
                'bonus_label_2_es' => 'Usa el código promocional HUGE',
                'bonus_label_2_fr' => 'Utilisez le code promo HUGE',
                'bonus_label_2_pt' => 'Use o código promocional HUGE',
                'warning_en' => '18+ only. Ts and Cs apply.',
                'warning_es' => 'Solo para mayores de 18 años. Se aplican términos y condiciones.',
                'warning_fr' => "Réservé aux 18 ans et plus. Conditions générales applicables.",
                'warning_pt' => 'Apenas para maiores de 18 anos. Aplicam-se termos e condições.',
                'licensed' => 'UK Gambling Commission',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'support-en@22bet.com',
                'phone' => '+357 99 816806',
                'active' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'linebet'],
            ['key' => 'linebet',
                'name' => 'Linebet',
                'url' => 'linebet.com',
                'logo' => 'linebet.svg',
                'logo_color' => '#204f14',
                'promo_code' => 'NEWBONUS',
                'bonus_available' => 1,
                'bonus_label_1_en' => '$130 Bonus',
                'bonus_label_1_es' => 'Bono de $130',
                'bonus_label_1_fr' => 'Bonus de $130',
                'bonus_label_1_pt' => 'Bônus de $130',
                'bonus_label_2_en' => 'Use promo code NEWBONUS',
                'bonus_label_2_es' => 'Usa el código promocional NEWBONUS',
                'bonus_label_2_fr' => 'Utilisez le code promo NEWBONUS',
                'bonus_label_2_pt' => 'Use o código promocional NEWBONUS',
                'warning_en' => 'Register with Promo code NEWBONUS. 18+. T&Cs apply.',
                'warning_es' => 'Regístrate con el código promocional NEWBONUS. 18+. Aplican términos y condiciones.',
                'warning_fr' => "Inscrivez-vous avec le code promo NEWBONUS. 18+. Termes et conditions s'appliquent.",
                'warning_pt' => 'Registe-se com o código promocional NEWBONUS. 18+. Aplicam-se termos e condições.',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'support-in@linebet.com',
                'phone' => '+44 20 4577 0803',
                'active' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '20bet'],
            ['key' => '20bet',
                'name' => '20BET',
                'url' => '20bet.com',
                'logo' => '20bet.svg',
                'logo_color' => '#081d36',
                'promo_code' => 'MISSING',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Welcome Bonus €100',
                'bonus_label_1_es' => 'Bono de bienvenida del €100',
                'bonus_label_1_fr' => 'Bonus de bienvenue de €100',
                'bonus_label_1_pt' => 'Bónus de boas-vindas de €100',
                'bonus_label_2_en' => '+120 free spins on your first deposit',
                'bonus_label_2_es' => '+120 giros gratis en tu primer depósito',
                'bonus_label_2_fr' => '+120 tours gratuits sur votre premier dépôt',
                'bonus_label_2_pt' => '+120 rodadas grátis no seu primeiro depósito',
                'warning_en' => 'Register and get welcome bonus €100.',
                'warning_es' => 'Regístrate y recibe un bono de bienvenida de 100€.',
                'warning_fr' => 'Inscrivez-vous et recevez un bonus de bienvenue de 100€.',
                'warning_pt' => 'Registe-se e receba um bónus de boas-vindas de 100€.',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'support@20bet.com',
                'phone' => '',
                'active' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'betandyou'],
            ['key' => 'betandyou',
                'name' => 'BETANDYOU',
                'url' => 'betandyou-301409.top',
                'logo' => 'betandyou.svg',
                'logo_color' => '#000000',
                'promo_code' => 'MAXBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => 'Deposit $130 Get $130',
                'bonus_label_1_es' => 'Deposita $130 y recibe $130',
                'bonus_label_1_fr' => 'Déposez $130 et recevez $130',
                'bonus_label_1_pt' => 'Deposite $130 e receba $130',
                'bonus_label_2_en' => '130% with promo code MAXBONUS',
                'bonus_label_2_es' => '130% con el código promocional MAXBONUS',
                'bonus_label_2_fr' => '130% avec le code promo MAXBONUS',
                'bonus_label_2_pt' => '130% com o código promocional MAXBONUS',
                'warning_en' => 'Use the promo code MAXBONUS to get 30% extra for €130 welcome bonus. 18+ only. T&Cs apply.',
                'warning_es' => 'Usa el código promocional MAXBONUS para obtener un 30% extra en el bono de bienvenida de 130€. Solo para mayores de 18 años. Se aplican términos y condiciones.',
                'warning_fr' => "Utilisez le code promo MAXBONUS pour obtenir 30% supplémentaires sur le bonus de bienvenue de 130€. Réservé aux 18 ans et plus. Conditions générales applicables.",
                'warning_pt' => 'Use o código promocional MAXBONUS para obter 30% extra no bônus de boas-vindas de 130€. Apenas para maiores de 18 anos. Aplicam-se termos e condições.',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'support-en@betandyou.com',
                'phone' => '',
                'active' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => 'ivibet'],
            ['key' => 'ivibet',
                'name' => 'ivibet',
                'url' => 'ivibet.com',
                'logo' => 'ivibet.svg',
                'logo_color' => '#07C99A',
                'promo_code' => 'MAXBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => '$150 Free Bet',
                'bonus_label_1_es' => 'Apuesta gratuita de $130',
                'bonus_label_1_fr' => 'Pari gratuit de $130',
                'bonus_label_1_pt' => 'Aposta grátis de $130',
                'bonus_label_2_en' => 'Use promo code MAXBONUS',
                'bonus_label_2_es' => 'Usa el código promocional MAXBONUS',
                'bonus_label_2_fr' => 'Utilisez le code promo MAXBONUS',
                'bonus_label_2_pt' => 'Use o código promocional MAXBONUS',
                'warning_en' => '18+. T&Cs apply.',
                'warning_es' => '18+. Se aplican términos y condiciones.',
                'warning_fr' => "18+. Conditions générales applicables.",
                'warning_pt' => '18+. Aplicam-se termos e condições.',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'support@ivibet.com',
                'phone' => '',
                'active' => 1,
            ]
        );
        Bookmaker::query()->updateOrCreate(
            ['key' => '1xbit'],
            ['key' => '1xbit',
                'name' => '1xBit',
                'url' => '1xbit203865.top',
                'logo' => '1xbit.svg',
                'logo_color' => '#212121',
                'promo_code' => 'NEWBONUS',
                'bonus_available' => 0,
                'bonus_label_1_en' => '7 BTC bonus',
                'bonus_label_1_es' => 'Bono de 7 BTC',
                'bonus_label_1_fr' => 'Bonus de 7 BTC',
                'bonus_label_1_pt' => 'Bónus de 7 BTC',
                'bonus_label_2_en' => 'with promo code NEWBONUS',
                'bonus_label_2_es' => 'con el código promocional NEWBONUS',
                'bonus_label_2_fr' => 'avec le code promo NEWBONUS',
                'bonus_label_2_pt' => 'com o código promocional NEWBONUS',
                'warning_en' => '18+ only. Minimum deposit of 5 mBTC. 40x wagering applies. Ts and Cs apply.',
                'warning_es' => 'Solo mayores de 18 años. Depósito mínimo de 5 mBTC. Se aplica un requisito de apuesta de 40x. Aplican Términos y Condiciones.',
                'warning_fr' => "Réservé aux 18 ans et plus. Dépôt minimum de 5 mBTC. Conditions de mise de 40x. Termes et conditions s’appliquent.",
                'warning_pt' => 'Apenas para maiores de 18 anos. Depósito mínimo de 5 mBTC. Requisitos de aposta de 40x aplicam-se. Termos e Condições aplicáveis.',
                'licensed' => 'Curacao',
                'streaming' => 0,
                'tested' => 1,
                'email' => 'support-en@1x-bit.com',
                'phone' => '',
                'active' => 1,
            ]
        );
    }
}
